### ISSUE TITLE
[BUG] Caching of call_value().egld_value() breaks thing

### ISSUE THREAD

**Issue by janniksam** [multiversx/mx-sdk-rs#1051]
As discussed in discord, there is a a caching issue in call_value().egld_value().
I'm adding this for the sake of transparency here aswell:

@andrei-marinica already mentioned the following

> Oh, I know why the bug happens, it's related to the implementation of .egld_value(). It's cached, so we don't load it multiple times.
> It behaves, however, like an owned object, therefore the addition feels free to overwrite it. 
> The problem is that ownership is not implemented correctly for managed types. As a workaround, for now, a clone at line 27 prevents the issue.
> 
> I will need to rework some of the storage and the managed types with it, so a fix will be coming. Unfortunately, it takes quite a lot of redesign to pull off.

Here is the code to reproduce the issue:

```rs
#![no_std]

multiversx_sc::imports!();

#[multiversx_sc::contract]
pub trait FooSC: ContractBase {
    #[init]
    fn init(&self) {}

    #[endpoint(reproduce)]
    #[payable("*")]
    fn reproduce(&self) {
        self.verify_balance();
        self.send().direct_egld(
            &self.blockchain().get_caller(),
            &self.call_value().egld_value(),
        )
    }

    #[view(verify_balance)]
    fn verify_balance(&self) {
        // does NOT work
        let _balance_should_have = self.call_value().egld_value() + BigUint::from(1u64);

        // works
        // let _balance_should_have = BigUint::from(1u64) + self.call_value().egld_value();
    }
}
```

Repository (**branch: biguintbug**):
https://github.com/janniksam/mvx_sellnftbug/tree/biguintbug/mvx_sellnftbug

**Comment by andrei-marinica** [comment]
Issue fixed in PR https://github.com/multiversx/mx-sdk-rs/pull/1055

Currently released as framework version 0.40.0.
