### ISSUE TITLE
Scenario Checker for Transaction Logs in Rust Testing Framework

### ISSUE THREAD

**Issue by newtmex** [multiversx/mx-sdk-rs#1093]
Hi @andrei-marinica , any ETA for this: https://github.com/multiversx/mx-sdk-rs/blob/0ceeee0efc37dd133094e0f05187a605e6b518e0/vm/src/tx_execution/exec_general_tx.rs#L29 

This is causing failed test using the Rust Testing Framework. Or, is there any suggestion on how one can do anything about this?

**Comment by andrei-marinica** [comment]
Hi! We are in the process of changing the logging for transfers. It will come with the next protocol release. Until then just use `"address": "*"` in your tests.

**Comment by andrei-marinica** [comment]
The Rust VM now correctly immitates the logging of VM 1.5.
