### ISSUE TITLE
Bug : StaticApi is used for TxCall -> ContractCallWithEgld conversion

### ISSUE THREAD

**Issue by gfusee** [multiversx/mx-sdk-rs#1181]
StaticApi cannot (for obvious reasons) get transaction inputs, especially the caller's address.

However, the caller's address is required whenever there is 2 or more esdt payments, it leads to an issue where it is impossible to convert a such TxCall to ContractCallWithEgld with the current implementation.
Therefore, trying to do an sc call through an interactor leads to a panic.

Minimum reproductible example : 

```rust
let tx = ScCallStep::new()
        .esdt_transfer("str:WEGLD-abcdef", 0, 10u32)
        .esdt_transfer("str:USDC-abcdef", 0, 10u32);

tx.tx.to_contract_call(); 
```

**Comment by andrei-marinica** [comment]
Fixed in version 0.43.0.
