### ISSUE TITLE
Critical error: "Memory allocation forbidden" for promises callback with ManagedAddress parameter

### ISSUE THREAD

**Issue by gfusee** [multiversx/mx-sdk-rs#1372]
Here is a simple contract which throws the error: https://github.com/gfusee/promises-memory-alloc

Just deploy this contract on 2 different shards and call the "execute" endpoint on one of the contract by providing as parameter the address of the second one.

Here is a such transaction: https://devnet-explorer.multiversx.com/transactions/56c5fe7ba8e5191e3c2af811e203dea55a0240c8207b2b0049005dbc785a8a1e

This error makes async calls unusable with the Sirius release already deployed on the devnet

**Comment by andrei-marinica** [comment]
Have been investigating this since last week. I still haven't found the memory allocation issue, but will find it.

**Comment by andrei-marinica** [comment]
Issue fixed in release 0.46.0.
https://github.com/multiversx/mx-sdk-rs/releases/tag/v0.46.0
