### ISSUE TITLE
gitignore issue

### ISSUE THREAD

**Issue by icegriffinguru** [multiversx/mx-sdk-rs#962]
https://github.com/multiversx/mx-sdk-rs/blob/6af497a0d8bf849fd836b0b6812d43c2005d5bf2/contracts/examples/adder/.gitignore#L7

I think `output*` should be `output`.
I had an issue with it because `output_builder` module was ignored.

**Comment by andrei-marinica** [comment]
It's there because I occasionally create copies or backups of the output folder and want to ignore all.

Why do you have an `output_builder` module there? All modules are supposed to be under `src/`.

**Comment by icegriffinguru** [comment]
I usually use adder project as a template. ;))
`mxpy contract new test1 --template adder`

**Comment by andrei-marinica** [comment]
Should be `/output*/` so it doesn't recurse through subfolders. The wildcard is so as to also catch copies and backups of the output folder. 

Fixed in https://github.com/multiversx/mx-sdk-rs/pull/964

**Comment by icegriffinguru** [comment]
Thank you.
