### ISSUE TITLE
When deploying nft-minter: multiversx_sdk_network_providers.errors.GenericError: Url = [https://devnet-api.elrond.com/transaction/send], error = {'data': None, 'error': 'transaction generation failed: invalid chain ID', 'code': 'internal_issue'}

### ISSUE THREAD

**Issue by alexisdavidson** [multiversx/mx-sdk-rs#966]
Hi, I'm trying to deploy the nft-minter smart contract manually.

It builds fine but upon deploying I get this error:
multiversx_sdk_network_providers.errors.GenericError: Url = [https://devnet-api.elrond.com/transaction/send], error = {'data': None, 'error': 'transaction generation failed: invalid chain ID', 'code': 'internal_issue'}

I do have a mxpy.json in the same directory with this content:
{
    "configurations": {
        "default": {
            "proxy": "https://devnet-api.elrond.com",
            "chainID": "D"
        }
    },
    "contract":{
        "deploy":{
            "verbose": true,
            "bytecode": "output/nft-minter.wasm",
            "recall-nonce": true,
            "pem": "../../../../wallet/wallet-owner.pem",
            "gas-limit": 59999999,
            "arguments": [50000000000000000, 3, 25, 7, 64, 1],
            "send": true,
            "outfile": "deploy-testnet.interaction.json"
        }
     }
}

and the chainID does look fine. Any idea?

**Comment by popenta** [comment]
Hello!

Just to confirm, do you have a `testnet.toml` file?
If yes you can delete that file and that should fix it, or use `--chain=D` and that should work regarding you having or not the `testnet.toml` file.
A fix will come in a future release of mxpy.

Let me know if it helped you.

**Comment by alexisdavidson** [comment]
That fixed it, thank you!
