### ISSUE TITLE
[Bug] Mandos Test fails with "Have: 10 (execution failed). Message: no managed buffer under the given handle", changing unrelated stuff affects the result

### ISSUE THREAD

**Issue by janniksam** [multiversx/mx-sdk-rs#979]
Took me some hours to pin down enough, but it seems like Mandos tests sometimes have a bug when it comes to calling the `self.send().sell_nft(...)` with a non-zero nonce.

# Scenario:
1. My test does call a endpoint `auctionClaim` in the auctions.rs file, which uses `sell_nft()`.

2. There is a completely different and unrelated endpoint `marketplaceBuy`, which also uses the `sell_nft`-function. The test DOES NOT use this endpoint, it is totally unrelated.

3. Changing the `marketplaceBuy`-endpoint will effect the `auctionClaim`-call by the test, even though it has NOTHING to do with it.

![image](https://user-images.githubusercontent.com/15337798/219867314-985ca55a-459b-4b07-a32f-749078185542.png)

# Minimal reproduce able example:

I shrank down my real live example to something more minimal.

In this repository you'll find a SC-project, where you can reproduce the bug.
There is a single mandos test, that will fail by default. 
Following the instructions in the `marketplace.rs`, the test will magically succeed, even though the changes should be unrelated.

[Repository to reproduce this bug](https://github.com/janniksam/mvx_sellnftbug/blob/master/mvx_sellnftbug/src/modules/marketplace.rs)

**Comment by andrei-marinica** [comment]
We are aware of a bug in the Rust to Wasm compiler, which sometimes messes up calls to functions with many arguments. It is very difficult to pin down, which is why we were not able to create some minimal test case and file an error report to the compiler community.

Thank you for investigating this. Unfortunately it is not something that originates in the framework, so it is difficult to fix.

This is the first instance when we see it manifest in a framework API call. A common workaround is having methods with fewer arguments, but in this case this is clearly not possible.

We are looking into it.

**Comment by janniksam** [comment]
Hey Andrei, 

does this mean, it will also happen in the real sc execution and isn't mandos-related I haven't tested my code in a real situation yet, even though I probably should have.

I would love to see any workaround, if it really happens in real scenarios, I wish you good luck finding something. 

PS:
One thing I will try out is wrap the `sell_nft`-method into another method, so both my consumers will use it the wrapper method instead and `sell_nft` will only have one occurance in my code. I will get back to you and report if this is a possible workaround.

**Comment by andrei-marinica** [comment]
I am doing an investigation of your code. Thanks for the minimal example, it is of great help.

**Comment by janniksam** [comment]
Just wanted to tell you, what I found out so far:

Still NOT working, when you write a wrapper like this:

![image](https://user-images.githubusercontent.com/15337798/220161477-a4095e3f-4087-49c9-9e3e-517a2f8b6bfc.png)

This is also NOT working (so its not a naming issue)

![image](https://user-images.githubusercontent.com/15337798/220162777-bfc595f1-c271-4e2b-bbf4-d0b34edace37.png)

However, after moving one of the arguments around, this DOES work fine now as a work around:

![image](https://user-images.githubusercontent.com/15337798/220161654-1b863f75-58a0-4501-89d1-9faccdd0fc42.png)

**So my conclusion:** It seems to be a very specific order of arguments, that your method needs to have.

**Comment by andrei-marinica** [comment]
We are still investigating this issue, which is related to the compiler and to Wasmer.
A workaround that sometimes works is setting `opt-level = 3` instead of `opt-level = "z"` under `[profile.release]` in the `Cargo.toml` file of the wasm crate.

**Comment by andrei-marinica** [comment]
This issue was reproduced by us and the community several times.

It was caused by Wasmer 1. Now, after the latest mainnet release, Wasmer 1 is no longer in use, and this issue does not reproduce anymore.
