### ISSUE TITLE
Some of the documentation links are probably dead after the project was renamed

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [multiversx/mx-sdk-rs#982]
When you click on this link it doesn't work
https://github.com/multiversx/mx-sdk-rs/blob/6bfd30940263477494759dcf5074a81657f3d756/contracts/examples/adder/interaction/Adder.erdjs.md#L3

**Comment by andrei-marinica** [comment]
That tutorial project was abandoned in favor of our current documentation.

We are also in a process of replacing all js interactors with Rust-based ones, so that file will soon disappear.

Thank you for pointing this out, we will clean up all the remaining deprecated resources.

**Comment by StackOverflowExcept1on** [comment]
@andrei-marinica when you talk about replacing js with rust do you mean `multiversx-sdk` will be used? I also see that `multiversx-sdk` is fully not documeted

**Comment by andrei-marinica** [comment]
The file in question was completely removed.
